<?php

declare(strict_types=1);

namespace Extraton\TonClient\Entity\Crypto;

use Extraton\TonClient\Entity\AbstractResult;

/**
 * Type ResultOfGenerateRandomBytes
 */
class ResultOfGenerateRandomBytes extends AbstractResult
{
    /**
     * Get generated bytes encoded in base64
     *
     * @return string
     */
    public function getBase64(): string
    {
        return $this->requireString('bytes');
    }
}
